### ISSUE TITLE
Reply on Mail error

### ISSUE THREAD

**Issue by WASDIT** [modoboa/modoboa-webmail#98]
Hello if you click on a Mail to Reply it came the error that the mail in the recipient field is wrong.
It is for example: [u'mail@mail.at'] so it ist wrong. can you change them to only the mail adress mail@mail.at
![bildschirmfoto 2017-09-15 um 1 16 31 pm](https://user-images.githubusercontent.com/31078768/30520019-1d34ce9c-9ba5-11e7-86ad-5badb2f64486.jpg)

**Comment by tonioo** [comment]
@WASDIT Which version of the webmail are you using? Did you upgrade it recently?

**Comment by WASDIT** [comment]
Webmail | 1.2.0

**Comment by tonioo** [comment]
It it was an upgrade, did you run the collectstatic command?

**Comment by WASDIT** [comment]
It was no upgrade, when i try it i got:

root@mail:/srv/modoboa/instance# python manage.py collectstatic

You have requested to collect static files at the destination
location as specified in your settings:

    /srv/modoboa/instance/sitestatic

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes

0 static files copied to '/srv/modoboa/instance/sitestatic', 2204 unmodified.

**Comment by WASDIT** [comment]
New updates?

**Comment by tonioo** [comment]
This issue has a already been fixed with a previous version (see https://github.com/modoboa/modoboa-webmail/issues/76) and I can't reproduce it... Can you try to remove the sitestatic folder and run the collectstatic command once again? Also make sure to empty your browser cache.

**Comment by WASDIT** [comment]
It seamed to be fixed now with the collectstatic command. i will close it now and if it is again i will reopen it.
Thanks ;)

**Comment by WASDIT** [comment]
Hey,
today one client of the customer tell me that it is still the same.
Not with every mail only with some.
<img width="790" alt="bildschirmfoto 2017-10-10 um 14 51 57 1" src="https://user-images.githubusercontent.com/31078768/31407180-38e188c6-ae04-11e7-868d-d21dfe3aeb99.png">

**Comment by tonioo** [comment]
Actually, this issue still happens with messages including a ``Reply-To`` header.
